FROM node:16 as build

WORKDIR /usr/src/app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /usr/share/nginx/html
COPY --from=build /usr/src/app/build /usr/share/nginx/html
